# Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/csc340_project?useSSL=false
spring.datasource.username=root
spring.datasource.password=

# JPA Hibernate auto DDL mode for MySQL
spring.jpa.hibernate.ddl-auto=update

# Spotify API (Client Credentials)
spotify.client-id=7963a2996c5d42dcb73d8f244b361e0c
spotify.client-secret=040be56e090e413fb911218fa8ff5a57